### ISSUE TITLE
workflow for TFs using instructors dashboard

### ISSUE THREAD

**Issue by ShannonRice** [Harvard-ATG/hxat#83]
From: Caitlin Ballotta Rajagopalan
Caitlin has been working on the DCE distance course Poetry in America (with Prof. Lisa New)
Also in JIRA as ANNO-135 
https://jira.huit.harvard.edu/browse/ANNO-135
----------------------
 it would be helpful to our TFs to have annotations aggregated by annotation object/prompt.  Yes, I think it would be our preference that, when you click on a student's name, an instructor see a list of poem titles / assignment names (so as to be able to check for completion).  And then, yes, if the instructor could click on a poem title / assignment name to see the relevant annotations organized in a similar table, that would be helpful, too (in the event that we ever wanted to grade on the basis of content, and not just completion).

While not essential, it might also be helpful to TFs if they could isolate the view to a particular content week--in order to make it easier to monitor how many prompts a student has responded to over the course of the week.  This would look something like: Student Name > Week of Content > Poem Title/Assignment Name > Annotation Text.   (Let me know if that doesn't make sense!)

**Comment by arthurian** [comment]
1. *Performance*: The dashboard times out when it tries to load all the annotations for the Poetry in America course: `504 GATEWAY_TIMEOUT`. 
2. *Functionality*: Ability to group annotations by assignment and then sort within that group by assignment, student name, etc. Also add ability to search/filter within those results to find specific students or assignments. I believe this would allow the instructor to solve their use case above where a given week of content might span several assignments.
